# Generated by Django 5.2 on 2025-07-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_testimonial_name_remove_testimonial_photo_and_more'),
        ('pharmacy', '0007_order_orderitem'),
    ]

    operations = [
    ]
